import { ArrowLeft, CalendarDays, CheckCircle2, Download, FileSpreadsheet, FileText, Printer, UserRound } from 'lucide-react';
import { formatDate, formatDateTime } from '../utils/formatters.js';
import {
  downloadReportAsCsv,
  downloadReportAsExcel,
  downloadReportAsPrintHtml,
  formatNumber,
  parseDepartmentInsights,
} from '../utils/reportUtils.js';

export function ReportDetails({ report, onBack }) {
  if (!report) {
    return (
      <div className="content">
        <section className="page-title">
          <h1>Report Details</h1>
          <p>Home / Report Details</p>
        </section>

        <section className="panel ticket-details">
          <h2>No report selected</h2>
          <button className="primary-action" type="button" onClick={onBack}>
            <ArrowLeft size={16} />
            Back to Reports
          </button>
        </section>
      </div>
    );
  }

  const departmentInsights = parseDepartmentInsights(report.departmentInsights);

  return (
    <div className="content">
      <section className="page-title split-title">
        <div>
          <h1>Report Details</h1>
          <p>Home / View Reports / Details</p>
        </div>
        <div className="detail-actions">
          <button className="ghost-inline" type="button" onClick={() => downloadReportAsCsv(report)}>
            <Download size={16} />
            CSV
          </button>
          <button className="ghost-inline" type="button" onClick={() => downloadReportAsExcel(report)}>
            <FileSpreadsheet size={16} />
            Excel
          </button>
          <button className="ghost-inline" type="button" onClick={() => downloadReportAsPrintHtml(report)}>
            <Printer size={16} />
            PDF
          </button>
          <button className="ghost-inline" type="button" onClick={onBack}>
            <ArrowLeft size={16} />
            Back
          </button>
        </div>
      </section>

      <section className="panel ticket-details">
        <div className="ticket-header">
          <div className="ticket-icon">
            <FileText size={28} />
          </div>
          <div>
            <span className="ticket-label">Report Ticket</span>
            <h2>{report.name}</h2>
            <strong className="report-number">Report No: {report.id ? `#${report.id}` : 'Draft'}</strong>
          </div>
          <span className="status ticket-status">{report.status || 'Completed'}</span>
        </div>

        <div className="report-detail-layout">
          <div className="ticket-summary">
            <InfoIcon icon={CheckCircle2} label="Status" value={report.status || 'Completed'} />
            <InfoIcon icon={UserRound} label="Generated By" value={report.generatedBy} />
            <InfoIcon icon={CalendarDays} label="Generated On" value={formatDateTime(report.generatedOn)} />
          </div>

          <div className="description-block">
            <span>Description</span>
            <p>{report.description || 'No description provided for this report.'}</p>
          </div>

          <div className="ticket-main">
            <div className="section-kicker">Report Summary</div>
            <div className="detail-grid">
              <Detail label="Report No" value={report.id ? `#${report.id}` : 'Draft'} />
              <Detail label="Report Name" value={report.name} />
              <Detail label="Report Type" value={report.reportType} />
              <Detail label="Department" value={report.department || 'All Departments'} />
              <Detail label="Format" value={report.format || 'PDF'} />
              <Detail label="Date From" value={formatDate(report.dateFrom)} />
              <Detail label="Date To" value={formatDate(report.dateTo)} />
              <Detail label="Date Range" value={report.dateRange || `${formatDate(report.dateFrom)} - ${formatDate(report.dateTo)}`} />
              <Detail label="Total Value" value={formatNumber(report.totalValue)} />
              <Detail label="Average Value" value={formatNumber(report.averageValue)} />
            </div>

            <div className="report-content">
              <div className="section-kicker">Department Calculations</div>
              <div className="insight-grid">
                {departmentInsights.map((insight) => (
                  <Detail key={insight.label} label={insight.label} value={formatNumber(insight.value)} />
                ))}
              </div>
              {!departmentInsights.length && <div className="empty-state">No department calculations stored.</div>}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

function InfoIcon({ icon: Icon, label, value }) {
  return (
    <div className="ticket-info">
      <span><Icon size={16} /></span>
      <div>
        <small>{label}</small>
        <strong>{value || '-'}</strong>
      </div>
    </div>
  );
}

function Detail({ label, value }) {
  return (
    <div className="detail-item">
      <span>{label}</span>
      <strong>{value || '-'}</strong>
    </div>
  );
}
